// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aycoipidfgpomsovgmsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Y29pcGlkZmdwb21zb3ZnbXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTE0MTMsImV4cCI6MjA2NzQ4NzQxM30._iPR5sp3v9ut24D5k-Vf8YIuO2W3yKWhWlRB0uEGOGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});